// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIk4OVIY-cgyF0weRrugVr9JpC4Zcsp_w',
    appId: '1:208221952824:web:ac5ec689330f59a525ffcd',
    messagingSenderId: '208221952824',
    projectId: 'construction-site-46999',
    authDomain: 'construction-site-46999.firebaseapp.com',
    storageBucket: 'construction-site-46999.appspot.com',
    measurementId: 'G-5YTNBX9T3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO6VpqvY1nCh5HoXzISoqPA-LEyJ5vvfM',
    appId: '1:208221952824:android:efc39e1f6482e10925ffcd',
    messagingSenderId: '208221952824',
    projectId: 'construction-site-46999',
    storageBucket: 'construction-site-46999.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pp28Yg_G35m0rSjOXgPH_cWX8ETiU98',
    appId: '1:208221952824:ios:4b86334f3342485a25ffcd',
    messagingSenderId: '208221952824',
    projectId: 'construction-site-46999',
    storageBucket: 'construction-site-46999.appspot.com',
    iosBundleId: 'com.example.siteConstruct',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8pp28Yg_G35m0rSjOXgPH_cWX8ETiU98',
    appId: '1:208221952824:ios:4b86334f3342485a25ffcd',
    messagingSenderId: '208221952824',
    projectId: 'construction-site-46999',
    storageBucket: 'construction-site-46999.appspot.com',
    iosBundleId: 'com.example.siteConstruct',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIk4OVIY-cgyF0weRrugVr9JpC4Zcsp_w',
    appId: '1:208221952824:web:c2e26df22d14736925ffcd',
    messagingSenderId: '208221952824',
    projectId: 'construction-site-46999',
    authDomain: 'construction-site-46999.firebaseapp.com',
    storageBucket: 'construction-site-46999.appspot.com',
    measurementId: 'G-JN7F4QBZVX',
  );
}
